### ISSUE TITLE
android linking issue  RN62

### ISSUE THREAD

**Issue by a-eid** [luggit/react-native-config#442]
almost a fresh installation of RN 62 and I'm getting the following error when trying to link the lib.

```
info Linking "react-native-config" Android dependency
error Linking "react-native-config" failed. Run CLI with --verbose flag for more details.
Error: ENOENT: no such file or directory, open '.../android/src/main/res/values/strings.xml'
    at Object.openSync (fs.js:457:3)
    at Object.readFileSync (fs.js:359:35)
    at applyPatch (.../node_modules/@react-native-community/cli-platform-android/build/link/patches/applyPatch.js:42:51)
    at Object.registerNativeAndroidModule [as register] (.../node_modules/@react-native-community/cli-platform-android/build/link/registerNativeModule.js:33:27)
    at .../node_modules/@react-native-community/cli/build/commands/link/linkDependency.js:63:16
    at Array.forEach (<anonymous>)
    at linkDependency (/node_modules/@react-native-community/cli/build/commands/link/linkDependency.js:36:32)
    at async Object.link [as func] (.../node_modules/@react-native-community/cli/build/commands/link/link.js:110:5)
    at async Command.handleAction (.../node_modules/@react-native-community/cli/build/index.js:186:9)
```

**Comment by lesmo** [comment]
`react-native-config` supports auto-linking starting with `v1.0.0`, you shouldn't have to do `react-native link react-native-config` anymore

**Comment by a-eid** [comment]
@lesmo yeah, auto linking is definitely working on IOS but I'm not having any luck with android with manual or auto linking, I'll try again and comment my findings back here..

**Comment by archansel** [comment]
Yup, auto linking not working in android. I'm using RN 0.61.5

**Comment by archansel** [comment]
After trying to redo all installation steps, I think I'm missing one crucial step in android (under **Extra step for Android**)
```
// 2nd line, add a new apply:
apply from: project(':react-native-config').projectDir.getPath() + "/dotenv.gradle"
```

After applying that line, it works in android

**Comment by AdamGerthel** [comment]
Perhaps this information ought to be added to the readme? It would be helpful to know that the library supports auto-linking
