### ISSUE TITLE
Seg fault on build, from "require json" in BuildDotenvConfig.ruby

### ISSUE THREAD

**Issue by tzusman** [luggit/react-native-config#84]
Solution: remove [`require "json"`](https://github.com/luggit/react-native-config/blob/master/ios/ReactNativeConfig/BuildDotenvConfig.ruby#L3)

Mac OS X 10.11.6
Xcode 8.2.1

```
/Users/tz/.rvm/gems/ruby-2.3.1/gems/json-2.0.3/lib/json/ext/parser.bundle: [BUG] Segmentation fault
ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]

-- Crash Report log information --------------------------------------------
   See Crash Report log file under the one of following:
     * ~/Library/Logs/CrashReporter
     * /Library/Logs/CrashReporter
     * ~/Library/Logs/DiagnosticReports
     * /Library/Logs/DiagnosticReports
   the more detail of.

-- Control frame information -----------------------------------------------
c:0014 p:-17564499976282 s:0065 e:000064 TOP    [FINISH]
c:0013 p:---- s:0063 e:000062 CFUNC  :require
c:0012 p:0115 s:0059 e:000058 METHOD /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55
c:0011 p:0009 s:0049 e:000048 CLASS  /Users/tz/.rvm/gems/ruby-2.3.1/gems/json-2.0.3/lib/json/ext.rb:7
c:0010 p:0011 s:0047 e:000046 CLASS  /Users/tz/.rvm/gems/ruby-2.3.1/gems/json-2.0.3/lib/json/ext.rb:6
c:0009 p:0017 s:0045 e:000044 TOP    /Users/tz/.rvm/gems/ruby-2.3.1/gems/json-2.0.3/lib/json/ext.rb:3 [FINISH]
c:0008 p:---- s:0043 e:000042 CFUNC  :require
c:0007 p:0115 s:0039 e:000038 METHOD /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55
c:0006 p:0019 s:0029 e:000028 CLASS  /Users/tz/.rvm/gems/ruby-2.3.1/gems/json-2.0.3/lib/json.rb:59
c:0005 p:0017 s:0027 e:000026 TOP    /Users/tz/.rvm/gems/ruby-2.3.1/gems/json-2.0.3/lib/json.rb:55 [FINISH]
c:0004 p:---- s:0025 e:000024 CFUNC  :require
c:0003 p:0115 s:0021 e:000020 METHOD /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55
c:0002 p:0007 s:0011 E:000500 EVAL   ./ReactNativeConfig/BuildDotenvConfig.ruby:3 [FINISH]
c:0001 p:0000 s:0002 E:001528 TOP    [FINISH]

./ReactNativeConfig/BuildDotenvConfig.ruby:3:in `<main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Users/tz/.rvm/gems/ruby-2.3.1/gems/json-2.0.3/lib/json.rb:55:in `<top (required)>'
/Users/tz/.rvm/gems/ruby-2.3.1/gems/json-2.0.3/lib/json.rb:59:in `<module:JSON>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Users/tz/.rvm/gems/ruby-2.3.1/gems/json-2.0.3/lib/json/ext.rb:3:in `<top (required)>'
/Users/tz/.rvm/gems/ruby-2.3.1/gems/json-2.0.3/lib/json/ext.rb:6:in `<module:JSON>'
/Users/tz/.rvm/gems/ruby-2.3.1/gems/json-2.0.3/lib/json/ext.rb:7:in `<module:Ext>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'

-- C level backtrace information -------------------------------------------

-- Other runtime information -----------------------------------------------

* Loaded script: ./ReactNativeConfig/BuildDotenvConfig.ruby

* Loaded features:

    0 enumerator.so
    1 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15/enc/encdb.bundle
    2 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15/enc/trans/transdb.bundle
    3 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15/rbconfig.rb
    4 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/compatibility.rb
    5 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/defaults.rb
    6 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/deprecate.rb
    7 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/errors.rb
    8 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/version.rb
    9 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/requirement.rb
   10 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/platform.rb
   11 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb
   12 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/exceptions.rb
   13 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_gem.rb
   14 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/thread.rb
   15 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/monitor.rb
   16 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb
   17 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems.rb
   18 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency.rb
   19 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/path_support.rb
   20 /Users/tz/.rvm/gems/ruby-2.3.1/gems/json-2.0.3/lib/json/version.rb
   21 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/ostruct.rb
   22 /Users/tz/.rvm/gems/ruby-2.3.1/gems/json-2.0.3/lib/json/generic_object.rb
   23 /Users/tz/.rvm/gems/ruby-2.3.1/gems/json-2.0.3/lib/json/common.rb

[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
Don't forget to include the above Crash Report log file.
For details: http://www.ruby-lang.org/bugreport.html

/Users/tz/Library/Developer/Xcode/DerivedData/[project]-edimcnimpngwvqgyygsvlakwlmoc/Build/Intermediates/ReactNativeConfig.build/Debug-iphonesimulator/ReactNativeConfig.build/Script-EBE4E8281C7BF689000F8875.sh: line 2: 31002 Abort trap: 6           ./ReactNativeConfig/BuildDotenvConfig.ruby
Command /bin/sh failed with exit code 134
```

**Comment by ekryski** [comment]
I'm also seeing this with ruby-2.4.0

**Comment by ekryski** [comment]
Related to #13 I think. Using ruby with this has been causing a bunch of people all sorts of problems.

**Comment by ssansovich** [comment]
Adding that I also have this issue, and the suggested fix did indeed fixed it for me.

**Comment by mcavaliere** [comment]
I was seeing this with ruby 2.3.3. Upgrading to 2.4.1 seems to have resolved it.

**Comment by seanadkinson** [comment]
Is the owner active?  Is there a reason for the `require`?  Obviously a simple PR if its an acceptable solution.  This issue affects my builds frequently.

**Comment by pedro** [comment]
So sorry for the trouble folks, the require was removed/things should be working normally now on the latest. Thanks!
